version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ec2-user/GraphQL-Company-Api
hooks:
  AfterInstall:
    - location: scripts/install_dependency.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
